using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MUFramework.SourceGenerator
{
    [Generator]
    public class UIOpenArgsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax c
                        && c.Modifiers.Any(SyntaxKind.PartialKeyword)
                        && c.BaseList != null,
                    transform: (ctx, _) => GetClassInfo(ctx))
                .Where(info => info != null);

            context.RegisterSourceOutput(candidates, (spc, info) =>
            {
                if (info == null) return;
                spc.AddSource($"{info.ClassName}.Generated.cs", GenerateSource(info));
            });
        }

        private ClassInfo? GetClassInfo(GeneratorSyntaxContext ctx)
        {
            var classDecl = (ClassDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol == null) return null;

            var openArgsInterfaces = symbol.AllInterfaces
                .Where(i => i.Name == "IOpenArgs" && i.ContainingNamespace.ToDisplayString() == "MUFramework")
                .ToList();

            if (!openArgsInterfaces.Any()) return null;

            return new ClassInfo
            {
                ClassName = symbol.Name,
                Namespace = symbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : symbol.ContainingNamespace.ToDisplayString(),
                Interfaces = openArgsInterfaces.Select(i => new OpenArgsInfo
                {
                    TypeArgs = i.TypeArguments.Select(t => t.ToDisplayString()).ToList()
                }).ToList()
            };
        }

        private string GenerateSource(ClassInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> DO NOT EDIT");
            sb.AppendLine("using System;");
            sb.AppendLine("using MUFramework;");
            sb.AppendLine();
            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            sb.AppendLine($"{indent}public partial class {info.ClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    internal override void OnOpenInternal(object[] args)");
            sb.AppendLine($"{indent}    {{");

            foreach (var iface in info.Interfaces)
            {
                var types = iface.TypeArgs;
                var conditions = new List<string>();
                for (int i = 0; i < types.Count; i++)
                {
                    conditions.Add($"args[{i}] is {types[i]} _a{i}");
                }

                var argList = string.Join(", ", Enumerable.Range(0, types.Count).Select(i => $"_a{i}"));
                var ifaceType = $"IOpenArgs<{string.Join(", ", types)}>";
                sb.AppendLine($"{indent}        if (args != null && args.Length == {types.Count} && {string.Join(" && ", conditions)})");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            (({ifaceType})this).OnOpen({argList});");
                sb.AppendLine($"{indent}            NotifyWidgetsOpen();");
                sb.AppendLine($"{indent}            return;");
                sb.AppendLine($"{indent}        }}");
            }

            sb.AppendLine($"{indent}        base.OnOpenInternal(args);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }

        private class ClassInfo
        {
            public string ClassName { get; set; } = "";
            public string? Namespace { get; set; }
            public List<OpenArgsInfo> Interfaces { get; set; } = new();
        }

        private class OpenArgsInfo
        {
            public List<string> TypeArgs { get; set; } = new();
        }
    }
}
