using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace MUFramework.Editor
{
    public abstract class UIBindingNamingRule
    {
        public abstract IReadOnlyDictionary<string, Type> PrefixMap { get; }

        public abstract string ToTargetClassName(UIGeneratorContext context);

        public abstract string ToTargetNamespace(UIGeneratorContext context);

        // 字段命名：Img_Icon -> _img_icon
        public virtual string ToFieldName(string nodeName, string matchedPrefix)
        {
            var trimmedPrefix = matchedPrefix.TrimEnd('_').ToLower();
            var suffix = nodeName.Substring(matchedPrefix.Length).ToLower();
            if (string.IsNullOrEmpty(suffix))
                return "_" + trimmedPrefix;
            return "_" + trimmedPrefix + "_" + suffix;
        }

        // 文件头注释行
        public virtual IEnumerable<string> ToFileHeaderLines()
        {
            yield return "// <auto-generated>";
            yield return "// DO NOT EDIT - generated by UIBindingCodeGenerator";
            yield return "// </auto-generated>";
        }

        // using 指令
        public virtual IEnumerable<string> ToUsingDirectives()
        {
            yield return "using UnityEngine;";
        }

        // 字段声明行
        public virtual string ToFieldDeclaration(string indent, string typeName, string fieldName)
            => $"{indent}private {typeName} {fieldName};";

        // AutoBind 方法签名行
        public virtual string ToAutoBindMethodDeclaration(string indent)
            => $"{indent}protected override void AutoBindComponents()";

        // 单条绑定赋值语句
        public virtual string ToBindStatement(string indent, string fieldName, string typeName, string escapedPath)
        {
            if (typeName == typeof(GameObject).FullName)
                return $"{indent}{fieldName} = Transform.Find(\"{escapedPath}\")?.gameObject;";
            return $"{indent}{fieldName} = Transform.Find(\"{escapedPath}\")?.GetComponent<{typeName}>();";
        }

        public (string fieldName, Type componentType)? TryMatch(string nodeName)
        {
            foreach (var (prefix, type) in PrefixMap)
            {
                if (nodeName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    return (ToFieldName(nodeName, prefix), type);
                }
            }
            return null;
        }

        protected static string ToPascalIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "UIBindingTarget";
            }

            var builder = new StringBuilder();
            var upperNext = true;
            foreach (var ch in value)
            {
                if (char.IsLetterOrDigit(ch))
                {
                    builder.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
                    upperNext = false;
                }
                else
                {
                    upperNext = true;
                }
            }

            if (builder.Length == 0)
            {
                return "UIBindingTarget";
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, "UI");
            }

            return builder.ToString();
        }
    }
}
