using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace MUFramework.Editor
{
    public static class UIBindingCodeGenerator
    {
        public static void Generate(UIBindingCollector collector, string outputDir)
        {
            if (collector == null || string.IsNullOrEmpty(collector.TargetClassName)) return;
            if (collector.Entries == null || collector.Entries.Count == 0) return;
            outputDir = MUIConfig.NormalizeAssetPath(outputDir);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> DO NOT EDIT - generated by UIBindingCodeGenerator");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(collector.TargetNamespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {collector.TargetNamespace}");
                sb.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : "";
            sb.AppendLine($"{indent}public partial class {collector.TargetClassName}");
            sb.AppendLine($"{indent}{{");
            foreach (var entry in collector.Entries)
            {
                sb.AppendLine($"{indent}    private {entry.ComponentType} {entry.FieldName};");
            }

            sb.AppendLine();
            sb.AppendLine($"{indent}    internal override void AutoBindComponents()");
            sb.AppendLine($"{indent}    {{");
            foreach (var entry in collector.Entries)
            {
                var escapedPath = entry.Path.Replace("\\", "\\\\").Replace("\"", "\\\"");
                if (entry.ComponentType == "UnityEngine.GameObject")
                {
                    sb.AppendLine($"{indent}        {entry.FieldName} = Transform.Find(\"{escapedPath}\")?.gameObject;");
                }
                else
                {
                    sb.AppendLine($"{indent}        {entry.FieldName} = Transform.Find(\"{escapedPath}\")?.GetComponent<{entry.ComponentType}>();");
                }
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            Directory.CreateDirectory(Path.Combine(Application.dataPath, "..", outputDir));
            var filePath = Path.Combine(outputDir, $"{collector.TargetClassName}.AutoBind.cs");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
            Debug.Log($"[MUI] Generated: {filePath}");
        }
    }
}
